# Generated by Django 4.2.1 on 2023-05-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('zipp_code', models.IntegerField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('id_number', models.IntegerField(blank=True, null=True)),
                ('tax_number', models.IntegerField(blank=True, null=True)),
                ('account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('foundation_date', models.DateField(blank=True, null=True)),
                ('representative', models.CharField(blank=True, max_length=255, null=True)),
                ('activity', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
