# Generated by Django 4.2.1 on 2023-05-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='zipp_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
