# Generated by Django 4.2.1 on 2023-05-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_company_zipp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Puni naziv'),
        ),
    ]
