# Generated by Django 4.2.1 on 2023-05-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_company_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Skraćeni naziv'),
        ),
    ]
