# Generated by Django 4.2.1 on 2023-05-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_company_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tekući račun'),
        ),
        migrations.AlterField(
            model_name='company',
            name='activity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Delatnost'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mesto'),
        ),
        migrations.AlterField(
            model_name='company',
            name='foundation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum osnivanja'),
        ),
        migrations.AlterField(
            model_name='company',
            name='id_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Matični broj'),
        ),
        migrations.AlterField(
            model_name='company',
            name='representative',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Zastupnik'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Poreski broj'),
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pravni oblik'),
        ),
        migrations.AlterField(
            model_name='company',
            name='zipp_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Poštanski broj'),
        ),
    ]
