# Generated by Django 4.2.1 on 2023-05-17 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_company_account_number_alter_company_activity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Kancelarija', 'verbose_name_plural': 'Kancelarije'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Korisnik', 'verbose_name_plural': 'Korisnici'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company'),
        ),
    ]
