# Generated by Django 4.2.1 on 2023-05-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Kancelarija')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Zahtev za registraciju',
                'verbose_name_plural': 'Zahtevi za registraciju',
            },
        ),
    ]
