# Generated by Django 4.2.1 on 2023-05-17 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_registerreq'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerreq',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 5, 17, 11, 13, 53, 955968, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
