# Generated by Django 4.2.1 on 2023-05-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_registerreq_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_full_access',
            field=models.BooleanField(default=False),
        ),
    ]
