# Generated by Django 4.2.1 on 2023-05-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_has_full_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerreq',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Administrator'),
        ),
    ]
