# Generated by Django 4.2.1 on 2023-05-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_registerreq_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='has_full_access',
            field=models.BooleanField(default=False, verbose_name='Administrator'),
        ),
        migrations.AlterField(
            model_name='registerreq',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
