# Generated by Django 4.2.1 on 2023-05-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_customuser_has_full_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_open_subject',
            field=models.BooleanField(default=False, verbose_name='Otvara projekte'),
        ),
    ]
