# Generated by Django 4.2.1 on 2023-05-24 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customuser_can_open_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assosiate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Ime')),
                ('last_name', models.CharField(max_length=255, verbose_name='Prezime')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company', verbose_name='kancelarija')),
            ],
            options={
                'verbose_name': 'Saradnik',
                'verbose_name_plural': 'Saradnici',
            },
        ),
    ]
