# Generated by Django 4.2.1 on 2023-05-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_assosiate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assosiate',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Zanimanje'),
        ),
    ]
