# Generated by Django 4.2.1 on 2023-05-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_customuser_can_add_assosiate_customuser_can_add_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assosiate',
            name='company',
        ),
        migrations.AddField(
            model_name='assosiate',
            name='company',
            field=models.ManyToManyField(to='accounts.company', verbose_name='kancelarija'),
        ),
    ]
