# Generated by Django 4.2.1 on 2023-05-29 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Stranka', 'verbose_name_plural': 'Stranke'},
        ),
    ]
