# Generated by Django 4.2.1 on 2023-05-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_client_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_add_client',
            field=models.BooleanField(default=False, verbose_name='Dodaje Stranke'),
        ),
    ]
