# Generated by Django 4.2.1 on 2023-06-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_customuser_can_add_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tip korisnika'),
        ),
        migrations.RemoveField(
            model_name='client',
            name='company',
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ManyToManyField(to='accounts.company', verbose_name='Kancelarija'),
        ),
    ]
