# Generated by Django 4.2.2 on 2023-06-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_assosiate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Matični broj'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Poreski broj'),
        ),
        migrations.AlterField(
            model_name='company',
            name='zipp_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Poštanski broj'),
        ),
    ]
