# Generated by Django 4.2.3 on 2023-08-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_company_id_number_alter_company_tax_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='grider_login_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Grider login name'),
        ),
        migrations.AddField(
            model_name='company',
            name='grider_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Grider password'),
        ),
    ]
