# Generated by Django 4.2.3 on 2023-08-09 10:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_company_grider_login_name_company_grider_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ime modula')),
            ],
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.DateField(default=datetime.date.today)),
                ('server_time', models.FloatField(blank=True, null=True)),
                ('modul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.modul', verbose_name='Modul')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Korisnik')),
            ],
        ),
    ]
