# Generated by Django 4.2.3 on 2023-08-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_modul_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='licence_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Broj licence'),
        ),
    ]
