# Generated by Django 4.2.3 on 2023-08-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_customuser_licence_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='licence',
            name='pin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PIN'),
        ),
    ]
