# Generated by Django 4.2.3 on 2023-09-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_licence_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ispostava'),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='company',
            name='telefon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='company',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='region'),
        ),
    ]
