# Generated by Django 4.2.1 on 2023-10-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_company_department_company_email_company_telefon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Obrazovanje'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefon_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Broj telefona'),
        ),
    ]
