from django.urls import path
from . import views

app_name = 'main'


urlpatterns = [
    path('', views.index, name="index"),
    path('users/', views.users, name="users"),
    path('assosiates/', views.assosiates, name="assosiates"),
    path('subject/<int:pk>', views.subject, name="subject"),
    path('subjects/', views.subjects, name="subjects"),
    path('clients/', views.clients, name="clients"),
    path('companies/', views.companies, name="companies"),
    path('company-stats/', views.company_stats, name="company-stats"),
    path('open-subject/', views.open_subject, name="open-subject"),
    path('edit-subject/<int:pk>', views.edit_subject, name="edit-subject"),
    path('js-submit-subject-form/<int:pk>', views.js_submit_subject_form, name="js-submit-subject-form"),
    path('get-file', views.get_file_from_aws, name="get-file"),
    path('return-aws-preview', views.return_aws_preview, name="return-aws-preview"),
    path('return-aws-pdf', views.return_aws_pdf, name="return-aws-pdf"),
    path('return-aws-png', views.return_aws_png, name="return-aws-png"),
    path('register-lot/<int:pk>', views.register_lot, name="register-lot"),
    path('add-lot-object/<str:lotNumber>/<int:pk>', views.add_lot_object, name="add-lot-object"),
    path('grider-etrf2000-gk7', views.grider_etrf2000_gk7, name="grider-etrf2000-gk7"),
    path('grider-gk7-etrf2000', views.grider_gk7_etrf2000, name="grider-gk7-etrf2000"),
    path('grider-nvt2-trst', views.grider_nvt2_trst, name="grider-nvt2-trst"),
    path('grider-trst-nvt2', views.grider_trst_nvt2, name="grider-nvt2-trst"),
    path('add-comment/<int:pk>', views.add_comment, name="add-comment"),
    path('add-comment-to-db', views.add_comment_to_db, name="add-comment-to-db"),
    path('add-template/<int:pk>', views.add_template, name="add-template"),
    path('gps-devices/', views.gps_devices, name="gps-devices"),
    path('add-gps-device', views.add_gps_device, name="add-gps-device"),
    path('edit-gps-device/<int:id>', views.edit_gps_device, name="edit-gps-device"),
    path('upload-file-to-bucket', views.upload_file_to_bucket, name="upload-file-to-bucket"),
    path('upload-pdf-to-subject', views.upload_pdf_to_subject, name="upload-pdf-to-subject"),
    path('upload-grider-file-to-bucket', views.upload_grider_file_to_bucket, name="upload-grider-file-to-bucket"),
    path('e-salter/<int:pk>', views.e_salter, name="e-salter"),
    path('grider/<int:pk>', views.grider, name="grider"),
    path('cad/<int:pk>', views.cad, name="cad"),
    path('upload-cad-file-aws', views.upload_cad_file_aws, name="upload-cad-file-aws"),
    path('upload-grider-osr-file-to-bucket', views.upload_grider_osr_file_to_bucket, name="upload-grider-osr-file-to-bucket"),
    path('upload-grider-osr-pdf-to-bucket', views.upload_grider_osr_pdf_to_bucket, name="upload-grider-osr-pdf-to-bucket"),
    path('upload-elaborat-root-file', views.upload_elaborat_root_file, name="upload-elaborat-root-file"),
    path('delete-grider-file', views.delete_grider_file, name="delete-grider-file"),
    path('elaborat/<int:pk>', views.elaborat, name="elaborat"),
    path('elaborat/<int:pk>/<str:end>', views.elaborat, name="elaborat"),
    path('elaborat-full-preview', views.elaborat_full_preview, name="elaborat-full-preview"),
    path('edit-elaborat', views.edit_elaborat, name="edit-elaborat"),
    path('reset-elaborat/<int:pk>', views.reset_elaborat, name="reset-elaborat"),
    path('pdf-editor/<int:pk>/<str:aws>/<str:folder>', views.pdf_editor, name="pdf-editor"),
    path('pdf-editor/<int:pk>/<str:aws>/<str:folder>/<str:assemble>', views.pdf_editor, name="pdf-editor"),
    path('upload-elaborat-document', views.upload_elaborat_document, name="upload-elaborat-document"),
    path('upload-grider-elaborat-document', views.upload_grider_elaborat_document, name="upload-grider-elaborat-document"),
    path('upload-completed-elaborat', views.upload_completed_elaborat, name="upload-completed-elaborat"),
]
