# Generated by Django 4.2.1 on 2023-05-25 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0016_alter_assosiate_profession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Datum')),
                ('text', models.TextField(verbose_name='Komentar')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Korisnik')),
            ],
            options={
                'verbose_name': 'Komentar',
                'verbose_name_plural': 'Komentari',
            },
        ),
        migrations.CreateModel(
            name='SubjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.BooleanField(verbose_name='Ime i Prezime')),
                ('client_city', models.BooleanField(verbose_name='Mesto stanovanja')),
                ('client_address', models.BooleanField(verbose_name='Adresa stranke')),
                ('client_contact', models.BooleanField(verbose_name='Kontakt stranke')),
                ('lot_number', models.BooleanField(verbose_name='Broj parcele')),
                ('field_worker', models.BooleanField(verbose_name='Terenski radnik')),
                ('office_worker', models.BooleanField(verbose_name='Kancelarijski radnik')),
                ('assosiate', models.BooleanField(verbose_name='Saradnik')),
                ('delivery_date', models.BooleanField(verbose_name='Datum izrade')),
                ('cadastral_number', models.BooleanField(verbose_name='Broj predmeta u katastru')),
                ('cadastral_office', models.BooleanField(verbose_name='Katastarska služba')),
                ('subject_apply_date', models.BooleanField(verbose_name='Datum prijave predmeta')),
                ('measuring_date', models.BooleanField(verbose_name='Datum merenja')),
                ('field_lookup_date', models.BooleanField(verbose_name='Datum izlaska na teren')),
                ('expected_finish_date', models.BooleanField(verbose_name='Završetak izrade predmeta')),
                ('jmbg', models.BooleanField()),
                ('scanned_documents', models.BooleanField(verbose_name='Skenirani dokumenti')),
                ('installation_length', models.BooleanField(verbose_name='Metara za instalaciju')),
            ],
            options={
                'verbose_name': 'Tip predmeta',
                'verbose_name_plural': 'Tipovi predmeta',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Ime i Prezime')),
                ('client_city', models.CharField(max_length=255, verbose_name='Mesto stanovanja')),
                ('client_address', models.CharField(max_length=255, verbose_name='Adresa stranke')),
                ('client_contact', models.CharField(max_length=255, verbose_name='Kontakt stranke')),
                ('lot_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Broj parcele')),
                ('cadastral_municipality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Katastarska opština')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Faza predmeta')),
                ('price', models.IntegerField(verbose_name='Cena')),
                ('cadastral_price', models.IntegerField(blank=True, null=True, verbose_name='Trošak katastra')),
                ('payment_day', models.DateField(blank=True, null=True, verbose_name='Datum plaćanja')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Datum izrade')),
                ('cadastral_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Broj predmeta u katastru')),
                ('cadastral_office', models.CharField(blank=True, max_length=255, null=True, verbose_name='Katastarska služba')),
                ('subject_apply_date', models.DateField(blank=True, null=True, verbose_name='Datum prijave predmeta')),
                ('measuring_date', models.DateField(blank=True, null=True, verbose_name='Datum merenja')),
                ('field_lookup_date', models.DateField(blank=True, null=True, verbose_name='Datum izlaska na teren')),
                ('expected_finish_date', models.DateField(blank=True, null=True, verbose_name='Završetak izrade predmeta')),
                ('jmbg', models.IntegerField(blank=True, null=True)),
                ('scanned_documents', models.BooleanField(verbose_name='Skenirani dokumenti')),
                ('installation_length', models.FloatField(blank=True, null=True, verbose_name='Metara za instalaciju')),
                ('assosiate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.assosiate', verbose_name='Saradnik')),
                ('comment', models.ManyToManyField(blank=True, null=True, to='main.comment', verbose_name='Komentar')),
                ('field_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terenski', to=settings.AUTH_USER_MODEL, verbose_name='Terenski radnik')),
                ('office_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kancelarijski', to=settings.AUTH_USER_MODEL, verbose_name='Kancelarijski radnik')),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.subjecttype', verbose_name='Tip posla')),
            ],
            options={
                'verbose_name': 'Predmet',
                'verbose_name_plural': 'Predmeti',
            },
        ),
    ]
