# Generated by Django 4.2.1 on 2023-05-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjecttype',
            name='name',
            field=models.CharField(default='naziv', max_length=255),
            preserve_default=False,
        ),
    ]
