# Generated by Django 4.2.1 on 2023-05-25 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_subjecttype_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjecttype',
            options={'verbose_name': 'Tip posla', 'verbose_name_plural': 'Tipovi poslova'},
        ),
    ]
