# Generated by Django 4.2.1 on 2023-05-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_subjecttype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='comment',
            field=models.ManyToManyField(to='main.comment', verbose_name='Komentar'),
        ),
    ]
