# Generated by Django 4.2.1 on 2023-05-25 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_subject_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjecttype',
            name='client_contact',
        ),
    ]
