# Generated by Django 4.2.1 on 2023-05-25 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_subjecttype_client_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjecttype',
            name='lot_number',
        ),
    ]
