# Generated by Django 4.2.1 on 2023-05-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_subjecttype_cadastral_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='cadastral_municipality',
            field=models.CharField(default='Novi Sad', max_length=255, verbose_name='Katastarska opština'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='client_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresa stranke'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='client_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mesto stanovanja'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ime i Prezime'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='lot_number',
            field=models.CharField(default='1', max_length=255, verbose_name='Broj parcele'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='payment_day',
            field=models.DateField(default='2022-11-11', verbose_name='Datum plaćanja'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='status',
            field=models.CharField(default='otvoren', max_length=255, verbose_name='Faza predmeta'),
            preserve_default=False,
        ),
    ]
