# Generated by Django 4.2.1 on 2023-05-25 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_subject_cadastral_municipality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.subject', verbose_name='Predmet'),
        ),
    ]
