# Generated by Django 4.2.1 on 2023-05-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_subject_cadastral_municipality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='scanned_documents',
            field=models.BooleanField(default=False, verbose_name='Skenirani dokumenti'),
        ),
    ]
