# Generated by Django 4.2.1 on 2023-05-26 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_remove_subjecttype_company_subject_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
