# Generated by Django 4.2.1 on 2023-05-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_subject_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='cadastral_municipality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Katastarska opština'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='client_contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kontakt stranke'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='lot_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Broj parcele'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='payment_day',
            field=models.DateField(blank=True, null=True, verbose_name='Datum plaćanja'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Faza predmeta'),
        ),
    ]
