# Generated by Django 4.2.1 on 2023-05-29 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_assosiate_company_assosiate_company'),
        ('main', '0016_alter_subject_cadastral_municipality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ime i prezime stranke')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mesto stanovanja stranke')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresa stranke')),
                ('contact', models.CharField(max_length=255, verbose_name='Kontakt stranke')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company', verbose_name='Kancelarija')),
            ],
        ),
    ]
