# Generated by Django 4.2.1 on 2023-05-29 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
