# Generated by Django 4.2.1 on 2023-05-29 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_client_options'),
        ('main', '0018_delete_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.client', verbose_name='Stranka'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='client_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mesto stanovanja stranke'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ime i prezime stranke'),
        ),
    ]
