# Generated by Django 4.2.1 on 2023-06-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_subject_client_remove_subject_client_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='data_returned',
            field=models.BooleanField(default='False', verbose_name='Podaci iz RGZ-a završeni'),
            preserve_default=False,
        ),
    ]
