# Generated by Django 4.2.1 on 2023-06-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_subject_data_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Uplaćeno'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='data_returned',
            field=models.BooleanField(default=False, verbose_name='Podaci iz RGZ-a završeni'),
        ),
    ]
