# Generated by Django 4.2.1 on 2023-06-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_subject_paid_alter_subject_data_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='signed',
            field=models.BooleanField(default='False', verbose_name='Potpisan'),
        ),
    ]
