# Generated by Django 4.2.1 on 2023-06-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_subject_signed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Katastar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(blank=True, max_length=255, null=True, verbose_name='Katastarska služba')),
                ('municipality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Katastarska služba')),
                ('cadastral_municipality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Katastarska služba')),
            ],
        ),
    ]
