# Generated by Django 4.2.1 on 2023-06-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_katastar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='katastar',
            options={'verbose_name': 'Katastar', 'verbose_name_plural': 'Katastri'},
        ),
    ]
