# Generated by Django 4.2.2 on 2023-06-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_subject_jmbg_remove_subjecttype_jmbg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='status',
            field=models.CharField(blank=True, default='POTREBNO PRIJAVITI RGZ-u', max_length=255, null=True, verbose_name='Faza predmeta'),
        ),
    ]
