# Generated by Django 4.2.2 on 2023-07-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_subject_cadastral_municipality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='cadastral_municipality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Katastarska opština'),
        ),
    ]
