# Generated by Django 4.2.2 on 2023-07-05 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_subject_cadastral_municipality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='cadastral_municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='katastarska_opstina', to='main.katastar', verbose_name='Katastarska opština'),
        ),
    ]
