# Generated by Django 4.2.3 on 2023-07-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_subject_cadastral_municipality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjecttype',
            old_name='cadastral_office',
            new_name='municipality',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='cadastral_office',
        ),
        migrations.AddField(
            model_name='subject',
            name='municipality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Opština'),
        ),
    ]
