# Generated by Django 4.2.3 on 2023-07-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_rename_cadastral_office_subjecttype_municipality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjecttype',
            name='municipality',
            field=models.BooleanField(verbose_name='Opština'),
        ),
    ]
