# Generated by Django 4.2.3 on 2023-07-19 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_subjecttype_municipality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Broj parcele')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcele',
            },
        ),
        migrations.CreateModel(
            name='LotObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Broj objekta')),
                ('purpose', models.CharField(max_length=255, verbose_name='Namena objekta')),
                ('storey', models.CharField(blank=True, max_length=255, null=True, verbose_name='Spratnost')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Naziv objekta')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresa')),
                ('owner', models.CharField(blank=True, max_length=255, null=True, verbose_name='Imalac prava')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lot', verbose_name='Objekat')),
            ],
            options={
                'verbose_name': 'Objekat',
                'verbose_name_plural': 'Objekti',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='lots',
            field=models.ManyToManyField(to='main.lot'),
        ),
    ]
