# Generated by Django 4.2.3 on 2023-07-25 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_subject_lots_lot_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='lot_number',
        ),
    ]
