# Generated by Django 4.2.3 on 2023-07-26 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_remove_subject_lot_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='subjects',
        ),
        migrations.AddField(
            model_name='lot',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.subject', verbose_name='Predmet'),
        ),
    ]
