# Generated by Django 4.2.3 on 2023-08-03 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_company_grider_login_name_company_grider_password'),
        ('main', '0037_remove_lot_subjects_lot_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpsDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Proizvođač')),
                ('model', models.CharField(max_length=255, verbose_name='Model')),
                ('serial_number', models.CharField(max_length=255, verbose_name='Serijski broj')),
                ('certificate', models.CharField(max_length=255, verbose_name='Broj sertifikata')),
                ('valid_until', models.DateField(verbose_name='Važi do')),
                ('type', models.CharField(max_length=255, verbose_name='Tip aparata')),
                ('xyz', models.BooleanField(default=False)),
                ('blh', models.BooleanField(default=False)),
                ('enh', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Kancelarija')),
            ],
        ),
    ]
