# Generated by Django 4.2.3 on 2023-08-03 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_company_grider_login_name_company_grider_password'),
        ('main', '0038_gpsdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsdevice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Kancelarija'),
        ),
    ]
