# Generated by Django 4.2.3 on 2023-08-14 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_modul_licence'),
        ('main', '0040_remove_gpsdevice_blh_remove_gpsdevice_enh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='opener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otvorio', to='accounts.company', verbose_name='Kancelarija'),
        ),
    ]
