# Generated by Django 4.2.3 on 2023-08-14 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0042_alter_subject_opener'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='opener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otvorio', to=settings.AUTH_USER_MODEL, verbose_name='Otvorio'),
        ),
    ]
