# Generated by Django 4.2.3 on 2023-08-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_subject_opener'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElaboratDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Naziv dokumenta')),
            ],
        ),
    ]
