# Generated by Django 4.2.3 on 2023-08-22 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_elaboratdocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elaboratdocument',
            options={'verbose_name': 'Elaborat dokument', 'verbose_name_plural': 'Elaborat dokumenti'},
        ),
    ]
