# Generated by Django 4.2.3 on 2023-08-23 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0047_rename_elaboratsubjectdocuments_elaboratsubjectdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='responsible_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odgovorno', to=settings.AUTH_USER_MODEL, verbose_name='Odgovorno lice'),
        ),
    ]
