# Generated by Django 4.2.3 on 2023-08-24 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_subjecttype_elaborat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elaborat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ime elaborata')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject', verbose_name='Predmet')),
            ],
            options={
                'verbose_name': 'Dokument predmeta',
                'verbose_name_plural': 'Dokumenti predmeta',
            },
        ),
        migrations.DeleteModel(
            name='ElaboratSubjectDocument',
        ),
    ]
