# Generated by Django 4.2.3 on 2023-08-24 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_elaborat_delete_elaboratsubjectdocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elaborat',
            options={},
        ),
        migrations.CreateModel(
            name='ElaboratSubjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.elaboratdocument', verbose_name='Dokument')),
                ('elaborat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.elaborat', verbose_name='Predmet')),
            ],
            options={
                'verbose_name': 'Dokument predmeta',
                'verbose_name_plural': 'Dokumenti predmeta',
            },
        ),
    ]
