# Generated by Django 4.2.3 on 2023-08-24 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_alter_elaborat_options_elaboratsubjectdocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elaborat',
            options={'verbose_name': 'Elaborat', 'verbose_name_plural': 'Elaborati'},
        ),
    ]
