# Generated by Django 4.2.3 on 2023-08-24 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_alter_elaborat_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elaboratsubjectdocument',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.elaboratdocument', verbose_name='Dokument'),
        ),
        migrations.AlterField(
            model_name='elaboratsubjectdocument',
            name='elaborat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.elaborat', verbose_name='Predmet'),
        ),
    ]
