# Generated by Django 4.2.3 on 2023-08-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_elaboratdocument_aws_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='elaboratdocument',
            name='uploaded',
            field=models.BooleanField(default=False, verbose_name='Uploded'),
        ),
    ]
