# Generated by Django 4.2.3 on 2023-08-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_elaboratdocument_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elaboratdocument',
            name='uploaded',
        ),
        migrations.AddField(
            model_name='elaboratsubjectdocument',
            name='uploaded',
            field=models.BooleanField(default=False, verbose_name='Uploaded'),
        ),
    ]
