# Generated by Django 4.2.3 on 2023-08-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_elaboratdocument_template_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='elaborattype',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
