# Generated by Django 4.2.3 on 2023-08-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_elaborattype_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='elaboratsubjectdocument',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
