# Generated by Django 4.2.3 on 2023-08-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_elaboratsubjectdocument_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='elaboratdocument',
            name='grider',
            field=models.BooleanField(default='False', verbose_name='Grider'),
        ),
    ]
