# Generated by Django 4.2.3 on 2023-09-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_elaboratdocument_grider'),
    ]

    operations = [
        migrations.AddField(
            model_name='elaboratdocument',
            name='cad',
            field=models.BooleanField(default='False', verbose_name='CAD'),
        ),
        migrations.AddField(
            model_name='elaboratdocument',
            name='content',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sadrzaj'),
        ),
    ]
