# Generated by Django 4.2.3 on 2023-09-15 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_elaboratdocument_cad_elaboratdocument_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gpsdevice',
            options={'verbose_name': 'Instrument', 'verbose_name_plural': 'Instrumenti'},
        ),
    ]
