# Generated by Django 4.2.3 on 2023-09-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_alter_gpsdevice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='canceled',
            field=models.BooleanField(default='False', verbose_name='Storniran'),
        ),
    ]
