# Generated by Django 4.2.3 on 2023-09-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_subject_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='elaboratdocument',
            name='root',
            field=models.BooleanField(default='False', verbose_name='Root'),
        ),
    ]
